- name: Cloudbuster
  hosts: myhosts
  become: true
  become_method: sudo
  tasks:
    - name: Create directory 
      ansible.builtin.file:
        path: /home/vaal/fairchild  
        state: directory
    - name: Install git
      ansible.builtin.apt:
        name: git
        state: present
    - name: Install cmake
      ansible.builtin.apt:
        name: cmake
        state: present
    # - name: Download FFTW
    #   ansible.builtin.get_url:
    #     url: https://www.fftw.org/fftw-3.3.10.tar.gz
    # - name: Extract FFTW from tarball
    #   ansible.builtin.unarchive:
    #     src: fftw-3.3.10.tar.gz
    #     dest: /home/vaal/fairchild/fftw-3.3.10

    - name: Pull portaudio
      ansible.builtin.git:
        repo: 'https://github.com/PortAudio/portaudio/'
        dest: /home/vaal/fairchild/portaudio

    - name: Pull rtmidi
      ansible.builtin.git:
        repo: 'https://github.com/thestk/rtmidi/'
        dest: /home/vaal/fairchild/rtmidi

    - name: Pull libsndfile
      ansible.builtin.git:
        repo: 'https://github.com/libsndfile/libsndfile/'
        dest: /home/vaal/fairchild/libsndfile

    - name: Pull libsamplerate 
      ansible.builtin.git:
        repo: 'https://github.com/libsndfile/libsamplerate/'
        dest: /home/vaal/fairchild/libsamplerate

    - name: Pull pffft 
      ansible.builtin.git:
        repo: 'https://github.com/marton78/pffft/'
        dest: /home/vaal/fairchild/pffft

    # - name: Pull matplotplusplus 
    #   ansible.builtin.git:
    #     repo: 'https://github.com/alandefreitas/matplotplusplus/'
    #     dest: /home/vaal/fairchild/matplotplusplus

    - name: Install ALSA devkit 
      ansible.builtin.apt:
        name: libasound-dev
        state: present
    - name: Copy files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /home/vaal/fairchild/
        owner: vaal
      with_items:
        - main.cpp
        - midi_controller.hpp
        - sampler.cpp
        - hanning.hpp
        - CMakeLists.txt
    - name: Copy samples 
      ansible.builtin.copy:
        src: "samples"
        dest: /home/vaal/fairchild/samples
        owner: vaal
    - name: Create build directory 
      ansible.builtin.file:
        path: /home/vaal/fairchild/build
        state: directory
    - name: Change to build directory 
      ansible.builtin.command: /home/vaal/fairchild/build
    - name: Build targets
      community.general.make:
        chdir: /home/vaal/fairchild/build
        target: all


    # - name: Copy binary 
    #   ansible.builtin.copy:
    #     src: ./build/fairchild
    #     dest: /usr/bin/fairchild
    #     owner: vaal

    # - name: Run program
    #   ansible.builtin.command: /usr/bin/fairchild